version: '3.9'

services:
   app:
      build: .
      container_name: blog_app
      env_file:
         - .env
      ports:
         - '3000:3000'
      volumes:
         - .:/app
         - /app/node_modules
      command: sh -c "npm install && npm run dev"
